server:
  port: 9090

spring:
  application:
    name: admin-server
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
  boot:
    admin:
      discovery:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:admin-server}
    nonSecurePort: 9090
    nonSecurePortEnabled: ${EUREKA_NON_SECURE_PORT_ENABLED:true}
    securePortEnabled: ${EUREKA_SECURE_PORT_ENABLED:false}
    securePort: ${EUREKA_SECURE_PORT:443}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.spendsmart: DEBUG
